Repository facelessuser/ColorHelper, pull requests merged in 2024-05, with the labels that each got.

#266 Opt-in to python 3.8 plugin host
  .python-version
Labels: C: infrastructure, S: approved

#264 Add color rule for INI syntax
  color_helper.sublime-settings
Labels: C: source, S: approved, C: settings

#268 Bump version and update changelog
  CHANGES.md
  messages.json
  messages/recent.md
  support.py
Labels: C: infrastructure, C: source, C: docs, S: approved

#270 Fix issue with API update
  CHANGES.md
  ch_picker.py
  messages/recent.md
  support.py
Labels: C: source, C: docs, S: approved
